import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <main>
        <section className="bg-blue-700 min-h-screen">
          <nav className="">
            <h1>Eric Xie</h1>
            <ul>
              <li>
                
              </li>
              <li><a href="#">Resume</a></li>
            </ul>
          </nav>
        </section>
      </main>
    </div>
  );
}
