import Head from 'next/head'
import { BsMoonFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub, AiOutlineInstagram, AiFillYoutube } from 'react-icons/ai';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <main className='bg-white px-10'>
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className='text-xl font-poppins font-bold text-blue'>Eric Xie.</h1>
            <ul className='flex items-center'>
              <li>
                <BsMoonFill className='cursor-pointer text-2xl'/>
              </li> 
              <li><a className='bg-blue text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='p-2'>
            <h2 className='text-7xl py-2 font-poppins font-thin'>Hi,</h2>
            <h1 className='text-6xl font-poppins font-bold underline decoration-blue tracking-tight'>I'm Eric Xie</h1>
            <h3 className='text-2xl font-poppins font-light py-2'>Software Developer</h3>
          </div>
          <nav className='py-3 px-2 mb-12 flex justify-left space-x-2 w-50 h-50'>
            <a class href="https://www.linkedin.com/in/ericcxie/"><AiFillLinkedin size={20}/></a>
            <a href="https://github.com/ericcxie"><AiFillGithub size={20}/></a>
            <a href="https://www.instagram.com/ericcxie/"><AiOutlineInstagram size={20}/></a>
            <a href="https://www.youtube.com/@ericcxie"><AiFillYoutube size={20}/></a>
          </nav>
        </section>
      </main>
    </div>
  );
}
