import Head from 'next/head'
import { BsMoonFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub, AiOutlineInstagram, AiFillYoutube } from 'react-icons/ai';
import Image from 'next/image';
import arrow from '../public/components/Arrow 2.svg'
import amafind from '../public/img/amafind.png'
import { FiMenu } from 'react-icons/fi';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <main className='bg-white px-10'>
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className='text-xl font-poppins font-bold text-blue'>Eric Xie.</h1>
            <ul className='flex items-center'>
              <li>
                <BsMoonFill className='cursor-pointer text-2xl'/>
              </li> 
              <li className='pl-3 pt-1'>
                <button>
                  <FiMenu className='text-4xl text-blue'/>
                </button>
              </li>
            </ul>
          </nav>
          <div className='pl-1'>
            <h2 className='text-7xl py-2 font-poppins font-thin'>Hi,</h2>
            <h1 className='text-6xl font-poppins font-bold underline decoration-blue tracking-tight'>I'm Eric Xie</h1>
            <h3 className='text-2xl font-poppins font-light py-2'>Software Developer</h3>
          </div>
          <div className='text-2xl flex justify-start gap-1 pl-1 py-1'>
            <a class href="https://www.linkedin.com/in/ericcxie/"><AiFillLinkedin/></a>
            <a href="https://github.com/ericcxie"><AiFillGithub/></a>
            <a href="https://www.instagram.com/ericcxie/"><AiOutlineInstagram/></a>
            <a href="https://www.youtube.com/@ericcxie"><AiFillYoutube/></a>
          </div>
          <div className='relative mx-auto py-20'>
            <Image className='mx-auto' src={arrow}/>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl font-poppins font-semibold'>Projects</h3>
          </div>
          <div>
            <div className='shadow-lg p-10 rounded-xl my-10'>

              <h3 className='text-xl font-medium'>AmaFind - Amazon Webscraper in Python</h3>
              <p className='italic pb-5'>Python, pandas, BeautifulSoup4</p>
              <Image src={amafind}/>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
